### ISSUE TITLE
Elaboração do Mapa Mental

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#10]
## Descrição da Issue
Elaboração do mapa mental para o processo de elicitação de requisitos.

### Tasks: 
- [x] Elaborar o mapa mental.

### Critérios de aceitação
- [x] Validar com todos os integrantes do grupo.

**Comment by sudjoao** [comment]
O @guilherme-mendes e eu nos reunimos hoje a noite e fizemos o mapa mental, estamos aguardando se validado pelo grupo para fechar a issue.
![Arquitetura e Desenho de Software - Mapa Mental Design Sprint (2)](https://user-images.githubusercontent.com/46005310/91920391-459b9200-ec9f-11ea-9810-d9fe3057a64b.jpg)
