### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EsioFreitas** [UnBArqDsw/2020.1_G13_iGado#19]
**Visão geral**
Não há um resumo da ideia de vcs e seria legal ter. Muito legal mostrar o histórico de edição e referências! No entanto, os documentos não têm versionamento. Outro ponto é que não mostra quem fez os documentos, tirando o caso 5w2h feito pelo Lucas e Caio. Fico com a impressão que somente eles trabalharam. 

**Politicas** 
Muito bom! Parabens! Mas recomendaria tirar da aba de “Produto”, pois isso é ligado ao desenvolvimento. 

**5W2H** 
O documento está genêrico e focado no projeto. No entanto, deve ser no problema. 
Por exemplo:
Por que? -  vcs  afirmam que o mercado está com escassez de aplicativos. No entanto, o Brasil é referência em tecnologia e ciência nessa área. Imagino que queiram falar de pequenos produtores. Logo é um aplicativo de nicho e vcs não mostraram isso.
Quem?	 - Aqui se refere a quem vc quer ajudar. Quem é o seu usuário ?
Onde?	Quando? - momentos que seu usuário vai usar sua solução. Quais são?
Como?	- “para facilitar a gestão rural “, Como? “forma que o proprietário possa ter um controle sobre os dados dos bovinos” como? 
Quanto custa? - como esse valor foi definido? Minha recomendação é que não coloque. A não ser que vcs fizeram um estudo e documento que comprove o valor.

**Mapa Mental**
Ta muito bom! Parabens! Ficou bem bonito e explicativo

**Diagrama de Ishikawa**
Muito bom!!

**Comment by sudjoao** [comment]
Muito obrigado pelos feedbacks @EsioFreitas , a gente vai levar eles em conta pra melhorar nossa documentação, quanto a questão da ideia do projeto a gente tava primeiro definindo o escopo para realmente decidir o que ia ser o foco do nosso projeto, estamos fazendo um documento de visão para definir isso certinho e dar a ideia do que é o app.

**Quem fez os documentos**
Sobre isso, no inicio de todas as páginas tem uma tabela de versionamento e lá fala quem foi o responsável por fazer o artefato, como mostrado nos prints abaixo.
![image](https://user-images.githubusercontent.com/46005310/92315911-fd43e300-efc2-11ea-97ac-4f53d1055686.png)
![image](https://user-images.githubusercontent.com/46005310/92315914-0634b480-efc3-11ea-999e-e3d89a22420e.png)

**Documentos não terem versionamento**
Não entendi muito o que você quis dizer com isso, no caso você acha que além de fazer a tabela de versionamento no inicio da página teríamos que fazer de outro jeito também?

**Comment by EsioFreitas** [comment]
Sobre a tabela de versionamento, ela não mostra quem o produziu e sim qual alterou o documento geral. Por exemplo: há os artefatos de rp. No começo desse artefato haverá a tabela de versionamento e em baixo todas as versões dos rps com seus respectivos criadores embaixo. 
Já sobre o versionamento, o que eu quero dizer é que vcs produziram apenas um documento X. Não houve um refinamento? Não houve versões dele? Vcs afirmaram que estão em processo de amadurecimento da ideia. Cade a prova disso? Cade os registro de amadurecimento da ideia? O versionamento prova isso. Ele serve para registrar a evolução do produto. Por exemplo: vc não chega e faz as telas de um app. Há um protótipo de baixo nivel -> medio -> alta fedelidade. Esses artefatos sao as provas de evolução e amadurecimento das telas e o registro delas são importantes. 

É isso! Qualquer coisa manda ae! =D
