### ISSUE TITLE
Elaborar diagrama de Ishikawa

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#6]
## Descrição da Issue
Elaborar o diagrama de Ishikawa para o processo de elicitação de requisitos.

### Tasks: 
- [x] Elaborar diagrama de Ishikawa.

### Critérios de aceitação
- [x] Validar com os membros do grupo.

**Comment by iurisevero** [comment]
![Diagrama de Causa-Efeito Desenho](https://user-images.githubusercontent.com/42645264/92156593-9b874b80-edff-11ea-968b-26585f2d9df2.png)
