### ISSUE TITLE
Documentar Fechamento da Sprint 5 e Abertura da Sprint 6

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#80]
## Descrição da Issue
Documentar as atas de fechamento e abertura das sprints 4 e 5, respectivamente.
### Tasks: 
- [x] Documentar sprint Review;
- [x] Documentar Sprint Retrospective
- [x] Documentar Planning Poker;
- [x] Documentar Sprint Planning.

### Critérios de aceitação
- [x] Todos os ritos documentos;
- [x] Documento seguindo o padrão criado.

**Comment by ghost** [comment]
<img width="980" alt="Screen Shot 2020-10-10 at 3 33 31 PM" src="https://user-images.githubusercontent.com/40740008/95667839-f5d3a480-0b41-11eb-83d6-2ee9c3c029de.png">

<img width="1250" alt="Screen Shot 2020-10-10 at 9 50 19 PM" src="https://user-images.githubusercontent.com/40740008/95667898-a2158b00-0b42-11eb-9c24-07f19265d47e.png">
